language: java
before_install:
- curl https://raw.github.com/liveSense/all/master/travis-settings.xml --create-dirs
  -o target/travis/settings.xml
- openjdk6
script:
- mvn deploy --settings target/travis/settings.xml
env:
  global:
  - secure: eKgngzJbMSrvAZvaZe1bhF/IKDydAE+H92ClUt4N1GNwkkwbbOsJayEkEa0ofCKj2+Oq4NOlGrfEZnMgW/U+jeHnpJ1Qr/1dmZ86M5Ao8gnDHT3YeXmY8gQqYJxbrhhCzpxHxhhvwNX019uCiMO1PivHWgyp877fDgdPa52Tf84=
  - secure: lkTt6NMz9et69iQ02zSlUVAn7W/n/d6jwvZy5CLbH6q22LJpxxT+HOTBWgm6NTF888VitwhJTPFwC9lUwl5asTMYApaAUxWhcY2DFEJJl2yiLWFtSffWesNmrJdKWfUwSMFyfiCKVQxcsqM5b6YmhjufgqMmSrrRPEUSPVJOrOY=
